from datetime import datetime
import json
from operator import itemgetter
import sys


def analyze(data: dict):
    artist_playcounts = {}
    track_playcounts = {}
    platforms = {}

    start = datetime.fromtimestamp(data[0]["timestamp"])
    end = datetime.fromtimestamp(data[-1]["timestamp"])

    for scrobble in data:
        try:
            artist_playcounts[scrobble["artist"]] += 1
        except KeyError:
            artist_playcounts[scrobble["artist"]] = 1

        try:
            track_playcounts[scrobble["artist"] + " - " + scrobble["track"]] += 1
        except KeyError:
            track_playcounts[scrobble["artist"] + " - " + scrobble["track"]] = 1

        try:
            platforms[scrobble["platform"]] += 1
        except KeyError:
            platforms[scrobble["platform"]] = 1

    print(
        "Analyzing",
        len(data),
        "Scrobbles between \033[1m",
        start,
        "\033[0m and \033[1m",
        end,
        "\033[0m",
    )
    print()
    print("\033[1m------ Top artists -------\033[0m")
    for i, (item, value) in enumerate(
        sorted(artist_playcounts.items(), key=itemgetter(1), reverse=True)[:25], start=1
    ):
        print(f"#{i:>3} \t {value} plays \t {item}")
    print()
    print("\033[1m------ Top  tracks -------\033[0m")
    for i, (item, value) in enumerate(
        sorted(track_playcounts.items(), key=itemgetter(1), reverse=True)[:25], start=1
    ):
        print(f"#{i:>3} \t {value} plays \t {item}")

    print()
    print("\033[1m------ Top platforms -------\033[0m")
    for i, (item, value) in enumerate(
        sorted(platforms.items(), key=itemgetter(1), reverse=True), start=1
    ):
        print(f"#{i:>3} \t {value} plays \t {item}")


def main(filename):
    with open(filename, "r") as f:
        data = json.load(f)
        analyze(data)


if __name__ == "__main__":
    if len(sys.argv) < 2 or sys.argv[1] in ["-h", "--help"]:
        print("Analyze a converted json file generated by convert.py")
        print()
        print("Usage:")
        print("\tpython analyze.py [path/to/json]")
        quit(1)
    main(sys.argv[1])
